using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using Cafe.Api.Services;
using System.ComponentModel.DataAnnotations;

namespace Cafe.Api.Models;

public class PurchaseOrder
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; }

    [BsonElement("outletId")]
    [BsonRepresentation(BsonType.ObjectId)]
    public string OutletId { get; set; } = string.Empty;

    [BsonElement("poNumber")]
    public string PoNumber { get; set; } = string.Empty;

    [BsonElement("ingredientId")]
    [BsonRepresentation(BsonType.ObjectId)]
    public string IngredientId { get; set; } = string.Empty;

    [BsonElement("ingredientName")]
    public string IngredientName { get; set; } = string.Empty;

    [BsonElement("supplierName")]
    public string SupplierName { get; set; } = string.Empty;

    [BsonElement("supplierContact")]
    public string? SupplierContact { get; set; }

    [BsonElement("quantity")]
    public decimal Quantity { get; set; }

    [BsonElement("unit")]
    public string Unit { get; set; } = string.Empty;

    [BsonElement("estimatedCost")]
    public decimal EstimatedCost { get; set; }

    [BsonElement("status")]
    public string Status { get; set; } = "pending"; // pending, approved, ordered, received, cancelled

    [BsonElement("isAutoGenerated")]
    public bool IsAutoGenerated { get; set; }

    [BsonElement("createdAt")]
    public DateTime CreatedAt { get; set; } = MongoService.GetIstNow();

    [BsonElement("updatedAt")]
    public DateTime UpdatedAt { get; set; } = MongoService.GetIstNow();
}

public class UpdatePurchaseOrderStatusRequest
{
    [Required]
    public string Status { get; set; } = string.Empty;
}
