import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { environment } from '../../environments/environment';
import { handleServiceError } from '../utils/error-handler';

export interface PurchaseOrder {
  id?: string;
  poNumber: string;
  ingredientId: string;
  ingredientName?: string;
  supplierName: string;
  quantity: number;
  unit?: string;
  estimatedCost: number;
  status: 'pending' | 'approved' | 'ordered' | 'received' | 'cancelled';
  isAutoGenerated: boolean;
  outletId?: string;
  createdAt?: string;
}

@Injectable({ providedIn: 'root' })
export class AutoReorderService {
  private http = inject(HttpClient);
  private apiUrl = environment.apiUrl;

  triggerAutoReorder(): Observable<{ message: string; purchaseOrders: PurchaseOrder[] }> {
    return this.http.post<{ message: string; purchaseOrders: PurchaseOrder[] }>(`${this.apiUrl}/manage/purchase-orders/auto-reorder`, {}).pipe(
      catchError(handleServiceError('AutoReorderService.triggerAutoReorder'))
    );
  }

  getPurchaseOrders(status?: string): Observable<PurchaseOrder[]> {
    const params = status ? `?status=${status}` : '';
    return this.http.get<PurchaseOrder[]>(`${this.apiUrl}/manage/purchase-orders${params}`).pipe(
      catchError(handleServiceError('AutoReorderService.getPurchaseOrders'))
    );
  }

  updatePurchaseOrderStatus(id: string, status: string): Observable<{ message: string }> {
    return this.http.put<{ message: string }>(`${this.apiUrl}/manage/purchase-orders/${id}/status`, { status }).pipe(
      catchError(handleServiceError('AutoReorderService.updatePurchaseOrderStatus'))
    );
  }
}
